/**
 * Project: Rock Paper Scissors
 * File: js/Game.js
 * Date: March 13, 2022
 * Description: Core logical unit for the Rock Paper Scissors application.
 *              Implements the "Game Logic" handling state, rules, and probabilistic outcome generation.
 * 
 * Authorship:
 * Created by: Amey Thakur (https://github.com/Amey-Thakur) & Mega Satish (https://github.com/msatmod)
 * Repository: https://github.com/Amey-Thakur/ROCK-PAPER-SCISSORS
 * License: MIT
 */

/**
 * Class representing the Game Logic.
 * Encapsulates the state of the game (scores, streak) and the rule evaluation engine.
 */
export default class Game {
    constructor() {
        // Initialize game state with zeroed values.
        // score: Tracks cumulative wins for player and computer.
        // streak: Tracks consecutive wins for the player (hook mechanism).
        this.score = {
            player: 0,
            computer: 0
        };
        this.streak = 0;
    }

    /**
     * Generates a pseudo-random choice for the computer.
     * 
     * @description
     * Utilizes the `Math.random()` function to generate a floating-point number between 0 (inclusive) and 1 (exclusive).
     * The domain [0, 1) is tri-sectored into three intervals to represent the discrete choices:
     * - [0, 0.34): Rock
     * - [0.34, 0.67): Paper
     * - [0.67, 1.0): Scissors
     * 
     * This ensures a uniform probability distribution (approx. 33.33%) for each outcome, assuming `Math.random()` is uniform.
     * 
     * @returns {string} The computer's choice ('rock', 'paper', or 'scissors').
     */
    getComputerChoice() {
        const rand = Math.random();
        if (rand < 0.34) {
            return 'rock';
        } else if (rand <= 0.67) {
            return 'paper';
        } else {
            return 'scissors';
        }
    }

    /**
     * Deterministic Evaluation of the Game Outcome.
     * 
     * @description
     * Evaluates the tuple (PlayerChoice, ComputerChoice) against the standard Rock-Paper-Scissors dominance hierarchy:
     * - Rock (R) > Scissors (S)
     * - Scissors (S) > Paper (P)
     * - Paper (P) > Rock (R)
     * 
     * @param {string} playerChoice - The choice selected by the user.
     * @param {string} computerChoice - The choice generated by the computer.
     * @returns {string} The result of the round: 'player', 'computer', or 'draw'.
     */
    getWinner(playerChoice, computerChoice) {
        if (playerChoice === computerChoice) {
            return 'draw';
        }

        // Outcome Matrix Interpretation
        if (playerChoice === 'rock') {
            return (computerChoice === 'paper') ? 'computer' : 'player';
        } else if (playerChoice === 'paper') {
            return (computerChoice === 'scissors') ? 'computer' : 'player';
        } else if (playerChoice === 'scissors') {
            return (computerChoice === 'rock') ? 'computer' : 'player';
        }

        // Fallback for unexpected inputs (Sanity Check)
        console.warn(`Unexpected input: ${playerChoice} vs ${computerChoice}`);
        return 'draw';
    }

    /**
     * State Transition: Process a completed round.
     * 
     * @description
     * Updates the internal state of the game based on the determined winner.
     * - Winner 'player': Increments player score and current streak.
     * - Winner 'computer': Increments computer score and resets streak (punishment mechanic).
     * - Winner 'draw': No state change to score or streak.
     * 
     * @param {string} winner - The result of the match.
     */
    updateScore(winner) {
        if (winner === 'player') {
            this.score.player++;
            this.streak++;
        } else if (winner === 'computer') {
            this.score.computer++;
            this.streak = 0; // Streak broken
        }
        // Draw maintains current state
    }

    /**
     * Reset Mechanism.
     * Returns the game state to initial conditions (t=0).
     */
    reset() {
        this.score = { player: 0, computer: 0 };
        this.streak = 0;
    }

    /**
     * Accessor for current score state.
     * @returns {object} Copy of the score object to prevent direct mutation reference.
     */
    getScore() {
        return { ...this.score };
    }

    /**
     * Accessor for current streak.
     * @returns {number} Current streak count.
     */
    getStreak() {
        return this.streak;
    }
}
